// This file is automatically generated. Do not modify it manually.

const firebaseConfig = {
  projectId: "studio-3883492113-4eb63",
  appId: "1:782506186625:web:b0d640b9360f98f4ab3a80",
  apiKey: "AIzaSyDyWr-f8sQN6WrY4HB757sk1EejhiMPgDQ",
  authDomain: "studio-3883492113-4eb63.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "782506186625"
};

export function getFirebaseConfig() {
  if (!firebaseConfig.apiKey || firebaseConfig.apiKey === 'your-api-key') {
    throw new Error('Missing or placeholder Firebase config: Please update src/firebase/config.ts with your Firebase project credentials.');
  }
  return firebaseConfig;
}
